<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolesAndPermissionsSeeder extends Seeder
{
    /** @var list<string> */
    private array $permissions = [
        'dashboard.view',
        'organization.view',
        'organization.manage',
        'users.manage',
        'clients.view',
        'clients.create',
        'clients.update',
        'clients.delete',
        'cases.view',
        'cases.create',
        'cases.update',
        'cases.delete',
        'case-notes.view',
        'case-notes.create',
        'case-notes.update',
        'case-notes.delete',
        'tasks.view',
        'tasks.create',
        'tasks.update',
        'tasks.delete',
        'calendar.view',
        'calendar.create',
        'calendar.update',
        'calendar.delete',
        'documents.view',
        'documents.create',
        'documents.update',
        'documents.delete',
        'documents.download',
        'intake-forms.view',
        'intake-forms.create',
        'intake-forms.update',
        'intake-forms.delete',
        'intake-submissions.view',
        'intake-submissions.create',
        'intake-submissions.update',
        'intake-submissions.delete',
        'intake-submissions.convert',
        'conflict-checks.view',
        'conflict-checks.create',
        'conflict-checks.update',
        'conflict-checks.delete',
        'time-entries.view',
        'time-entries.view-all',
        'time-entries.create',
        'time-entries.update',
        'time-entries.update-all',
        'time-entries.delete',
        'time-entries.delete-all',
        'time-entries.approve',
        'expenses.view',
        'expenses.view-all',
        'expenses.create',
        'expenses.update',
        'expenses.update-all',
        'expenses.delete',
        'expenses.delete-all',
        'invoices.view',
        'invoices.create',
        'invoices.update',
        'invoices.delete',
        'invoices.send',
        'invoices.record-payment',
        'trust.view',
        'trust.create',
        'trust.delete',
        'reports.view',
        'audit.view',
        'messages.view',
        'messages.create',
        'communication-logs.view',
        'communication-logs.create',
        'communication-logs.update',
        'communication-logs.delete',
        'client-contacts.view',
        'client-contacts.create',
        'client-contacts.update',
        'client-contacts.delete',
        'service-items.view',
        'service-items.create',
        'service-items.update',
        'service-items.delete',
        'appointments.view',
        'appointments.create',
        'appointments.update',
        'appointments.delete',
        'appointments.manage-availability',
        'notifications.view',
        'notifications.update',
        'portal.dashboard.view',
        'portal.cases.view',
        'portal.documents.view',
        'portal.documents.download',
        'portal.documents.upload',
        'portal.invoices.view',
        'portal.invoices.pay',
        'portal.messages.view',
        'portal.messages.create',
        'portal.appointments.view',
        'portal.appointments.book',
        'portal.intake.view',
        'portal.intake.submit',
        'ai.use',
        'ai.governance.view',
        'ai.providers.manage',
        'approvals.view',
        'approvals.submit',
        'approvals.review',
        'signatures.view',
        'signatures.send',
        'portal.signatures.view',
        'portal.signatures.sign',
        'portal.profile.update',
        'filings.view',
        'filings.create',
        'filings.update',
        'filings.delete',
        'court-forms.view',
        'court-forms.create',
        'court-forms.update',
        'evidence.view',
        'evidence.create',
        'evidence.update',
        'evidence.delete',
        'briefs.view',
        'briefs.create',
        'briefs.update',
        'briefs.delete',
        'motions.view',
        'motions.create',
        'motions.update',
        'motions.delete',
        'research.view',
        'research.create',
        'research.update',
        'research.delete',
        'ediscovery.view',
        'ediscovery.create',
        'ediscovery.update',
        'ediscovery.delete',
        'knowledge.view',
        'knowledge.create',
        'knowledge.update',
        'knowledge.delete',
        'projects.view',
        'projects.create',
        'projects.update',
        'projects.delete',
        'analytics.view',
        'training.view',
        'training.create',
        'training.update',
        'training.delete',
        'training.assign',
    ];

    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        foreach ($this->permissions as $permission) {
            Permission::findOrCreate($permission, 'web');
        }

        $all = Permission::all();

        $roleMap = [
            'System Admin' => $all->pluck('name')->all(),
            'Firm Admin' => [
                'dashboard.view', 'organization.view', 'organization.manage', 'users.manage',
                'clients.view', 'clients.create', 'clients.update', 'clients.delete',
                'cases.view', 'cases.create', 'cases.update', 'cases.delete',
                'case-notes.view', 'case-notes.create', 'case-notes.update', 'case-notes.delete',
                'tasks.view', 'tasks.create', 'tasks.update', 'tasks.delete',
                'calendar.view', 'calendar.create', 'calendar.update', 'calendar.delete',
                'documents.view', 'documents.create', 'documents.update', 'documents.delete', 'documents.download',
                'intake-forms.view', 'intake-forms.create', 'intake-forms.update', 'intake-forms.delete',
                'intake-submissions.view', 'intake-submissions.create', 'intake-submissions.update', 'intake-submissions.delete', 'intake-submissions.convert',
                'conflict-checks.view', 'conflict-checks.create', 'conflict-checks.update', 'conflict-checks.delete',
                'time-entries.view', 'time-entries.view-all', 'time-entries.create', 'time-entries.update', 'time-entries.update-all', 'time-entries.delete', 'time-entries.delete-all', 'time-entries.approve',
                'expenses.view', 'expenses.view-all', 'expenses.create', 'expenses.update', 'expenses.update-all', 'expenses.delete', 'expenses.delete-all',
                'invoices.view', 'invoices.create', 'invoices.update', 'invoices.delete', 'invoices.send', 'invoices.record-payment',
                'trust.view', 'trust.create', 'trust.delete',
                'reports.view',
                'audit.view',
                'messages.view', 'messages.create',
                'communication-logs.view', 'communication-logs.create', 'communication-logs.update', 'communication-logs.delete',
                'client-contacts.view', 'client-contacts.create', 'client-contacts.update', 'client-contacts.delete',
                'service-items.view', 'service-items.create', 'service-items.update', 'service-items.delete',
                'appointments.view', 'appointments.create', 'appointments.update', 'appointments.delete', 'appointments.manage-availability',
                'notifications.view', 'notifications.update',
                'ai.use', 'ai.governance.view', 'ai.providers.manage',
                'approvals.view', 'approvals.submit', 'approvals.review',
                'signatures.view', 'signatures.send',
                'filings.view', 'filings.create', 'filings.update', 'filings.delete',
                'court-forms.view', 'court-forms.create', 'court-forms.update',
                'evidence.view', 'evidence.create', 'evidence.update', 'evidence.delete',
                'briefs.view', 'briefs.create', 'briefs.update', 'briefs.delete',
                'motions.view', 'motions.create', 'motions.update', 'motions.delete',
                'research.view', 'research.create', 'research.update', 'research.delete',
                'ediscovery.view', 'ediscovery.create', 'ediscovery.update', 'ediscovery.delete',
                'knowledge.view', 'knowledge.create', 'knowledge.update', 'knowledge.delete',
                'projects.view', 'projects.create', 'projects.update', 'projects.delete',
                'analytics.view',
                'training.view', 'training.create', 'training.update', 'training.delete', 'training.assign',
            ],
            'Partner' => [
                'dashboard.view', 'organization.view',
                'clients.view', 'clients.create', 'clients.update',
                'cases.view', 'cases.create', 'cases.update',
                'case-notes.view', 'case-notes.create', 'case-notes.update',
                'tasks.view', 'tasks.create', 'tasks.update',
                'calendar.view', 'calendar.create', 'calendar.update',
                'documents.view', 'documents.create', 'documents.update', 'documents.download',
                'intake-forms.view', 'intake-forms.create', 'intake-forms.update',
                'intake-submissions.view', 'intake-submissions.create', 'intake-submissions.update', 'intake-submissions.convert',
                'conflict-checks.view', 'conflict-checks.create', 'conflict-checks.update',
                'time-entries.view', 'time-entries.view-all', 'time-entries.create', 'time-entries.update', 'time-entries.update-all', 'time-entries.delete', 'time-entries.approve',
                'expenses.view', 'expenses.view-all', 'expenses.create', 'expenses.update', 'expenses.update-all', 'expenses.delete',
                'invoices.view', 'invoices.create', 'invoices.update', 'invoices.send', 'invoices.record-payment',
                'trust.view', 'trust.create', 'trust.delete',
                'reports.view',
                'messages.view', 'messages.create',
                'communication-logs.view', 'communication-logs.create', 'communication-logs.update', 'communication-logs.delete',
                'client-contacts.view', 'client-contacts.create', 'client-contacts.update', 'client-contacts.delete',
                'service-items.view', 'service-items.create', 'service-items.update', 'service-items.delete',
                'appointments.view', 'appointments.create', 'appointments.update', 'appointments.manage-availability',
                'notifications.view', 'notifications.update',
                'ai.use', 'ai.governance.view',
                'approvals.view', 'approvals.submit', 'approvals.review',
                'signatures.view', 'signatures.send',
                'filings.view', 'filings.create', 'filings.update', 'filings.delete',
                'court-forms.view', 'court-forms.create', 'court-forms.update',
                'evidence.view', 'evidence.create', 'evidence.update', 'evidence.delete',
                'briefs.view', 'briefs.create', 'briefs.update', 'briefs.delete',
                'motions.view', 'motions.create', 'motions.update', 'motions.delete',
                'research.view', 'research.create', 'research.update', 'research.delete',
                'ediscovery.view', 'ediscovery.create', 'ediscovery.update', 'ediscovery.delete',
                'knowledge.view', 'knowledge.create', 'knowledge.update', 'knowledge.delete',
                'projects.view', 'projects.create', 'projects.update', 'projects.delete',
                'analytics.view',
                'training.view', 'training.create', 'training.update', 'training.delete', 'training.assign',
            ],
            'Lawyer' => [
                'dashboard.view', 'organization.view',
                'clients.view', 'clients.create', 'clients.update',
                'cases.view', 'cases.create', 'cases.update',
                'case-notes.view', 'case-notes.create', 'case-notes.update',
                'tasks.view', 'tasks.create', 'tasks.update',
                'calendar.view', 'calendar.create', 'calendar.update',
                'documents.view', 'documents.create', 'documents.update', 'documents.download',
                'intake-forms.view',
                'intake-submissions.view', 'intake-submissions.create', 'intake-submissions.update',
                'conflict-checks.view', 'conflict-checks.create',
                'time-entries.view', 'time-entries.create', 'time-entries.update', 'time-entries.delete',
                'expenses.view', 'expenses.create', 'expenses.update', 'expenses.delete',
                'invoices.view', 'invoices.create',
                'trust.view', 'trust.create',
                'messages.view', 'messages.create',
                'communication-logs.view', 'communication-logs.create', 'communication-logs.update',
                'client-contacts.view', 'client-contacts.create', 'client-contacts.update',
                'service-items.view',
                'appointments.view', 'appointments.create',
                'notifications.view', 'notifications.update',
                'ai.use',
                'approvals.view', 'approvals.submit', 'approvals.review',
                'signatures.view', 'signatures.send',
                'filings.view', 'filings.create', 'filings.update',
                'court-forms.view', 'court-forms.create', 'court-forms.update',
                'evidence.view', 'evidence.create', 'evidence.update',
                'briefs.view', 'briefs.create', 'briefs.update',
                'motions.view', 'motions.create', 'motions.update',
                'research.view', 'research.create', 'research.update',
                'ediscovery.view', 'ediscovery.create', 'ediscovery.update',
                'knowledge.view', 'knowledge.create', 'knowledge.update',
                'projects.view', 'projects.create', 'projects.update',
                'analytics.view',
                'training.view',
            ],
            'Paralegal' => [
                'dashboard.view', 'organization.view',
                'clients.view', 'cases.view', 'cases.update',
                'case-notes.view', 'case-notes.create',
                'tasks.view', 'tasks.create', 'tasks.update',
                'calendar.view', 'calendar.create',
                'documents.view', 'documents.create', 'documents.download',
                'intake-forms.view',
                'intake-submissions.view', 'intake-submissions.create', 'intake-submissions.update',
                'conflict-checks.view', 'conflict-checks.create',
                'time-entries.view', 'time-entries.create', 'time-entries.update', 'time-entries.delete',
                'expenses.view', 'expenses.create', 'expenses.update', 'expenses.delete',
                'invoices.view',
                'trust.view',
                'messages.view', 'messages.create',
                'communication-logs.view', 'communication-logs.create', 'communication-logs.update',
                'client-contacts.view', 'client-contacts.create', 'client-contacts.update',
                'service-items.view',
                'appointments.view', 'appointments.create', 'appointments.update',
                'notifications.view', 'notifications.update',
                'approvals.view', 'approvals.submit',
                'signatures.view', 'signatures.send',
                'filings.view', 'filings.create', 'filings.update',
                'court-forms.view', 'court-forms.create',
                'evidence.view', 'evidence.create', 'evidence.update',
                'briefs.view', 'briefs.create', 'briefs.update',
                'motions.view', 'motions.create', 'motions.update',
                'research.view', 'research.create', 'research.update',
                'ediscovery.view', 'ediscovery.create', 'ediscovery.update',
                'knowledge.view', 'knowledge.create', 'knowledge.update',
                'projects.view', 'projects.create', 'projects.update',
                'training.view',
            ],
            'Secretary' => [
                'dashboard.view', 'organization.view',
                'clients.view', 'clients.create',
                'cases.view',
                'tasks.view', 'tasks.create', 'tasks.update',
                'calendar.view', 'calendar.create', 'calendar.update',
                'documents.view', 'documents.create', 'documents.download',
                'intake-forms.view', 'intake-forms.create',
                'intake-submissions.view', 'intake-submissions.create', 'intake-submissions.update',
                'time-entries.view', 'time-entries.create', 'time-entries.update',
                'expenses.view', 'expenses.create', 'expenses.update',
                'invoices.view',
                'messages.view', 'messages.create',
                'communication-logs.view', 'communication-logs.create', 'communication-logs.update',
                'appointments.view', 'appointments.create', 'appointments.update',
                'notifications.view', 'notifications.update',
                'approvals.view', 'approvals.submit',
                'signatures.view', 'signatures.send',
            ],
            'Client' => [
                'portal.dashboard.view',
                'portal.cases.view',
                'portal.documents.view',
                'portal.documents.download',
                'portal.documents.upload',
                'portal.invoices.view',
                'portal.invoices.pay',
                'portal.messages.view',
                'portal.messages.create',
                'portal.appointments.view',
                'portal.appointments.book',
                'portal.intake.view',
                'portal.intake.submit',
                'portal.signatures.view',
                'portal.signatures.sign',
                'portal.profile.update',
                'notifications.view',
                'notifications.update',
            ],
            'Consultant' => ['cases.view', 'case-notes.view', 'tasks.view', 'calendar.view', 'documents.view', 'documents.download', 'time-entries.view', 'time-entries.create', 'time-entries.update', 'notifications.view', 'notifications.update'],
        ];

        foreach ($roleMap as $roleName => $perms) {
            $role = Role::findOrCreate($roleName, 'web');
            $role->syncPermissions($perms);
        }
    }
}
